name: Umfragen
version: 1.0
description: Plugin zur Erstellung und Ausfuehrung von Umfragen
author: XGCF
main: me.xgcf.umfragen.Umfragen
commands:
  umfragen:
    description: Command für alle Befehle für Umfragen
    usage: /umfragen <command> <args>
    aliases: uf, u